# Generated by Django 5.0.7 on 2024-07-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_created_menu_and_item_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.item'),
        ),
    ]
