# Generated by Django 5.0.7 on 2024-07-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_added_child_field_to_item_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='child',
            new_name='parent',
        ),
    ]
